#
# Copyright 2013-2019 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '10.16.0'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - JHI_PROFILE=dev
    - JHI_RUN_APP=1
    - JHI_PROTRACTOR=0
    - JHI_JDK=8
    # specific config
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - JHI_E2E_HEADLESS=true
    - JHI_SCRIPTS=$TRAVIS_BUILD_DIR/test-integration/scripts
    - NG_CLI_ANALYTICS="false"

#----------------------------------------------------------------------
# Install all tools and check configuration
#----------------------------------------------------------------------
before_install:
  - |
    if [[ $JHI_JDK = '11' ]]; then
        echo '*** Using OpenJDK 11'
        sudo add-apt-repository ppa:openjdk-r/ppa
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
        java -version
    else
        echo '*** Using OpenJDK 8 by default'
    fi
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Update NPM
  - npm install -g npm
  # Install Yarn

script: mvn clean verify
